name: Java CI with SonarCloud

on: [push, pull_request]

jobs:
  compilation-checks:
    name: Java ${{ matrix.java }} Compilation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17, 21]
        include:
          - java: 23
            experimental: true
          - java: 24-ea
            experimental: true
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    
    - name: Verify compilation
      run: |
        # Determine appropriate source/target based on Java version
        if [ ${{ matrix.java }} -lt 17 ]; then
          JAVA_SOURCE=1.8
          JAVA_TARGET=1.8
        else
          JAVA_SOURCE=21
          JAVA_TARGET=21
        fi
        
        echo "Testing compilation with Java ${{ matrix.java }} (source: $JAVA_SOURCE, target: $JAVA_TARGET)"
        
        mvn --batch-mode --no-transfer-progress \
          clean apache-rat:check compile test-compile \
          -Dmaven.compiler.source=$JAVA_SOURCE \
          -Dmaven.compiler.target=$JAVA_TARGET
        
        echo "✅ Java ${{ matrix.java }} compilation successful"

  sonar-analysis:
    name: SonarCloud Analysis
    needs: compilation-checks
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for SonarCloud analysis
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
    
    - name: Build with SonarCloud
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn --batch-mode --no-transfer-progress \
          clean verify \
          -Dmaven.compiler.source=21 \
          -Dmaven.compiler.target=21 \
          sonar:sonar \
          -Dsonar.projectKey=abdel505_collection-2 \
          -Dsonar.organization=abdel505 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.java.binaries=target/classes
