name: Java CI with SonarCloud
on: [push, pull_request]

jobs:
  compilation-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17, 21]  # Only stable JDKs (removed experimental)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: |
          JAVA_SOURCE=${{ matrix.java < 17 && '1.8' || '21' }}
          mvn --batch-mode --no-transfer-progress clean compile test-compile \
            -Dmaven.compiler.source=$JAVA_SOURCE \
            -Dmaven.compiler.target=$JAVA_SOURCE

  sonar-analysis:
    needs: compilation-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - run: |
          mvn --batch-mode --no-transfer-progress verify sonar:sonar \
            -Dsonar.projectKey=abdel505_collection-2 \
            -Dsonar.organization=abdel505 \
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
