name: Java CI with SonarCloud

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        java: [8, 11, 17, 21, 23]
        experimental: [false]
        include:
          - java: 24-ea
            experimental: true
        exclude:
          # Exclude Java 8-16 when running SonarCloud analysis
          - java: 8
            when: ${{ github.event_name == 'pull_request' }}
          - java: 11
            when: ${{ github.event_name == 'pull_request' }}
        
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0  # Needed for SonarCloud analysis

    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Determine Java version
      id: java-version
      run: |
        JAVA_VERSION=$(java -version 2>&1 | awk -F '"' '/version/ {print $2}' | cut -d. -f1)
        echo "Detected Java version: $JAVA_VERSION"
        echo "java_major=$JAVA_VERSION" >> $GITHUB_OUTPUT

    - name: Build with Maven (Java 8-16)
      if: steps.java-version.outputs.java_major < 17
      run: |
        mvn --errors --show-version --batch-mode --no-transfer-progress \
          clean install \
          -Dmaven.compiler.source=1.8 \
          -Dmaven.compiler.target=1.8

    - name: Build with Maven (Java 17+)
      if: steps.java-version.outputs.java_major >= 17
      run: |
        mvn --errors --show-version --batch-mode --no-transfer-progress \
          clean install \
          -Dmaven.compiler.source=21 \
          -Dmaven.compiler.target=21

    - name: SonarCloud Scan
      if: steps.java-version.outputs.java_major >= 17 && github.event_name == 'pull_request'
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=abdel505_collection-2
          -Dsonar.organization=abdel505
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.java.binaries=target/classes
          -Dsonar.java.source=21
